- .env_example
- .gitignore
- MANIFEST.in
- dbt/adapters/hive/connections.py
- setup.py
Testplan:
- copy .env_example to dbt/adapters/hive/.env
- edit dbt/adapters/hive/.env and change SNOWPLOW_ENDPOINT and SNOWPLOW_API_KEY to appropriate values
- run dbt debug
- check if instrumentation data is being recoded, see ticket internal ticket (https://jira.cloudera.com/browse/DBT-68)
> add instrumentation code

- dbt/include/hive/macros/adapters.sql
- dbt/include/hive/macros/materializations/incremental/incremental.sql
- dbt/include/hive/macros/materializations/incremental/strategies.sql
GH Ticket: https://github.com/cloudera/dbt-hive/issues/19
Internal Ticket: https://jira.cloudera.com/browse/DBT-258
Test plan:
Use the steps in the above ticket to generate incremental model and rerun.
The rerun should succeed.
> Address an issue where second run of incremental model was failing with dbt-hive-example

- dbt/include/hive/macros/materializations/incremental/strategies.sql
- dbt/include/hive/macros/materializations/incremental/validate.sql
Testplan:
1) Clone example repo: https://github.com/cloudera/dbt-hive-example
2) Modify models/marts/covid/covid_cases.sql to include the following config:
{{
config(
materialized='incremental',
incremental_strategy='merge',
unique_key='country',
merge_update_columns=['cases', 'deaths']
)
}}
3) Do dbt run --full-refresh
4) Then change the source table raw_cases to include more data and update some rows
5) Do dbt run - this should succeed with new data reflected in the incremental model
> Fix an issue with incremental merge where the merge SQL was not correctly generated

- dbt/adapters/hive/connections.py
- dbt/adapters/hive/impl.py
Adds no new logic, only code reformatting.
> reformat the code as per pep-8 standards

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/connections.py
Add cloudera instrumentation library file. No logic changes.
Dbt debug to make sure nothing is broken .
> Add cloudera tracking library+ cleanup old tracking

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/connections.py
Added:
Code for  generating unique ids and platform instrumentation
Reorganized imports using isort.
Testing: 
Ran dbt debug with changes to see changes
> Platform instrumentation

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/relation.py
- Refactored code before pushing out logic changes
-  Change user to username in cloudera tracking file
https://jira.cloudera.com/browse/DBT-385
dbt debug to make sure code is not broken by any formatting changes
> Model instrumentation refactoring

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/relation.py
- dbt/include/hive/macros/materializations/incremental/incremental.sql
- Add default type as table for target_relation
- Added instrumentation data for model types
- Removed print statements. 
[DBT-385](https://jira.cloudera.com/browse/DBT-385)
Incremental Model created and accessed
> Model instrumentation

- dbt/adapters/hive/connections.py
- dbt/adapters/hive/impl.py
Fetch user permissions when performing dbt debug for instrumentation
Internal: https://jira.cloudera.com/browse/DBT-387
With a dbt debug, check the output in logs/dbt.log, there should be an entry similar to:
17:14:10.792607 [debug] [Thread-1  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_hive_debug_and_fetch_permissions", "permissions": "[{\"database\": \"default\", \"table\": \"server\", \"partition\": \"[]\", \"column\": \"[]\", \"principal_name\": \"srv_dbt_demo_user\", \"principal_type\": \"USER\", \"privilege\": \"ALTER\", \"grant_option\": false, \"grant_time\": 0.0, \"grantor\": \"ranger\"}, {\"database\": \"default\", \"table\": \"server\", \"partition\": \"[]\", \"column\": \"[]\", \"principal_name\": \"srv_dbt_demo_user\", \"principal_type\": \"USER\", …
> Fetch user permissions when performing dbt debug for instrumentation

- dbt/adapters/hive/connections.py
Add connection related instrumentation.
Internal: https://jira.cloudera.com/browse/DBT-388
With a dbt debug, check the output in logs/dbt.log, there should be an entry similar to:
(Connection close)
15:22:32.298920 [debug] [Thread-6  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_hive_close", "connection_state": "closed", "elapsed_time": "12.54", "auth": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "af0d1791-29a7-4415-88b6-bdc34d4bcf87", "unique_host_hash": "cd2782200d6326126da659d53c3dfe44", "unique_user_hash": "3d23971613757087a31726e1b95f7b57", "unique_session_hash": "3bd8de5b61b414439cf16e9d96f06d46", "python_version": "3.9.12", "system": "Darwin", "machine": …
> Add connection related instrumentation.

- dbt/adapters/hive/__version__.py
- setup.py
bump version for pypi release
N/A
N/A
> bump version for pypi release

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/connections.py
Added instrumentation data to fetch cml environment variables if they exist
[Internal Jira DBT-389](https://jira.cloudera.com/browse/DBT-389)
- Tested locally adding environment variables to local system
- 
- tested on cml
> Cml profile instrumentation

- .env_example
- dbt/adapters/hive/__version__.py
- setup.py
Fix a typo in .env_example
NA
NA
> Fix env type

- setup.py
update impala version to stable 0.18
N/A
N/A
> update impyla to stable version

- dbt/adapters/hive/connections.py
> fix unused imports

- dbt/adapters/hive/impl.py
include warehouse version in instrumentation
Internal ticket: https://jira.cloudera.com/browse/DBT-455
for a valid dbt project profile, execute dbt run, the logs should contain an entry similar to:
13:04:07.453060 [debug] [Thread-9  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_hive_warehouse", "warehouse_version": "[{\"_c0\": \"3.1.3000.7.2.15.1-1 r386e2de0b8d5cb3f1803ec755243d43185505de6\"}]", "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "9fa8bd4a-dac0-405b-8d4c-5fad64a63b50", "unique_host_hash": "1d112e0b9a134c93debbcc6ba08a10f5", "unique_user_hash": "6444baa7f3e0fa703845a1ca38c973b6", "unique_session_hash": …
> include warehouse version in instrumentation

- README.md
- setup.py
update docs and dependency for kerberos support
N/A
N/A
> update readme and dependency for kerberos

- tests/conftest.py
cleanup conftest
move host and port number as env var
> cleanup conftest parameters

- dbt/adapters/hive/connections.py
- dbt/include/hive/macros/utils/concat.sql
- dbt/include/hive/macros/utils/escape_single_quotes.sql
- dbt/include/hive/macros/utils/position.sql
- dbt/include/hive/macros/utils/right.sql
- dbt/include/hive/macros/utils/split_part.sql
- tests/functional/adapter/test_utils.py
add tests related to cross db string macros
Ex: 
python -m pytest tests/functional/adapter/test_utils.py -k "TestReplace"
> cross db macro strings

- dbt/include/hive/macros/adapters.sql
- dbt/include/hive/macros/utils/timestamps.sql
move timestamp macro under utils
remove timestamp macro from adapter.sql
> Refactor timestamp macro

- dbt/include/hive/macros/utils/hash.sql
- tests/functional/adapter/test_utils.py
Add support for hash macro, and testing support for misc macros - testexcept, teststingliteral, testintersect,testlength,testsafecast
> hash and misc macros

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/connections.py
Adding dbt deployment environment instrumentation as a blob
Test Results:
Non-CML
", \"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"hive-1.1.4\", \"**dbt_deployment_env\": \"\"**}","created_at":"2022-10-27T10:53:40.782Z"}
CML
\"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"hive-1.1.4\", \"**dbt_deployment_env\": \"{ \\\"env\\\":\\\"cml\\\", \\\"version\\\":\\\"1.1.15\\\",\\\"description\\\":\\\"This runtime includes DBT upgraded packages dbt-impala=1.1.4,dbt-hive=1.1.4,dbt-spark-cde=1.1.4,dbt-spark-livy=1.1.5\\\",\\\"edition\\\":\\\"dbt custom runtime\\\",\\\"image\\\":\\\"test-image\\\"}\"}**","created_at":"2022-10-27T11:23:09.603Z"}
> Adding dbt deployment environment instrumentation

- dbt/adapters/hive/__version__.py
- setup.py
update version to dbt-hive 1.1.5
> bump version instrumentation branch

- dbt/adapters/hive/cloudera_tracking.py
- dbt/adapters/hive/connections.py
Cherry pick changes for dbt deployment environment variables from branch.
> Adding dbt deployment environment instrumentation (#65)

- README.md
- dbt/adapters/hive/__version__.py
- setup.py
* bump version number
* update README
> update version and README for 1.2 release

- dbt/adapters/hive/impl.py
- tests/functional/adapter/test_data_types.py
* add datatype tests
* address an issue with column tests that resulted in the tests failing
<pre>
python -m pytest tests/functional/adapter/test_data_types.py
collected 6 items
tests/functional/adapter/test_data_types.py ......                       [100%]
======================== 6 passed in 744.45s (0:12:24) =========================
</pre>
> add datatype tests

- dbt/adapters/hive/connections.py
See: https://github.com/cloudera/dbt-hive/issues/85
> strip comment when sql statment start with SET

- dbt/adapters/hive/.env
- dbt/include/hive/macros/adapters.sql
- dbt/include/hive/macros/materializations/incremental/strategies.sql
Hello Team,
We have added the following code changes 
* ability to create iceberg table e.g  `stored by iceberg ` will be inserted if `is_iceberg` is set to true
* file_format variable `{{ file_format_clause() }}` was at a wrong order causing issues fixed it. 
* Merge logic has been enhanced to handle multiple unique keys which merging https://github.com/hpasumarthi/dbt-hive/blob/icebergV2/dbt/include/hive/macros/materializations/incremental/strategies.sql#L61 
* added featured to columns if the merge logic is not matched. https://github.com/hpasumarthi/dbt-hive/blob/icebergV2/dbt/include/hive/macros/materializations/incremental/strategies.sql#L90 
https://jira.cloudera.com/browse/DBT-670 
* We have tested it internally 
- [ Yes] I have performed a self-review of my code
- [Notsure] I …
> Adding ability to work with Iceberg v1/v2

- CONTRIBUTING.md
Added how to contribute in the repo documentations
https://jira.cloudera.com/browse/DBT-710
Generate Contribution readme
> DBT-710: Added contribution documentation

- Makefile
- tests/conftest.py
For connecting to CDH cluster with endpoint containing username/password. During test, we need to set those variable appropriately.
https://jira.cloudera.com/browse/DBT-707
https://gist.github.com/niteshy/78193330bc8575e1ade87ebfac818ac1
> DBT-707: Setting the environment variable username & password for cdh_endpoint

- tests/functional/adapter/test_docs.py
1. To fix the test corrected the `id` data-type to `bigint`
2. Removed unwanted functions re-definition from test_docs.py as they are can directly used from the dbt test lib
https://jira.cloudera.com/browse/DBT-715
Before logs https://gist.github.com/niteshy/498a1830083838c62eeae6160c1444f3
After fix test run and logs https://gist.github.com/niteshy/f71fa31919878dd51bd8dc04151ed371
> DBT-715: Fixing the docs broken test ie id should be bigint

- README.md
- RELEASE_NOTES.md
- dbt/include/hive/macros/materializations/incremental/strategies.sql
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_table_type.py
Update documentation and added release notes
https://jira.cloudera.com/browse/DBT-732
Release Notes
Updated Readme
[README.pdf](https://github.com/cloudera/dbt-hive/files/12264935/README.pdf)
> DBT-732: Update the documentation and release notes for v1.4.0 release

- tests/functional/adapter/config_files.py
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_file_format.py
Added tests for different file formats like ORC, Parquet, etc. The issue was fixed as a part of #96
[DBT-737](https://jira.cloudera.com/browse/DBT-737)
https://gist.github.com/niteshy/a1a45d6b87340aa66e3524b7ff390764
> DBT-737: Added tests for different file formats

- README.md
Updating Readme with corrected features and reasons
[DBT-732](https://jira.cloudera.com/browse/DBT-732)
N/A
> Fixing the feature documentation in README

- tests/functional/adapter/test_basic.py
Adding tests for Incremental full refresh. As part of this test, Running full-refresh after ensuring incremental mode is working as expected.
Full refresh does the following:
Create a temp table as the model query.
Alters the main table to temp table.
Alters temp table to main table.
Drops the renamed main table
https://jira.cloudera.com/browse/DBT-713
https://gist.github.com/vamshikolanu/336a0d032d71376799c8b8daa460680c
CTAs:
https://gist.github.com/vamshikolanu/336a0d032d71376799c8b8daa460680c#file-gistfile1-txt-L561
Alter table statements:
https://gist.github.com/vamshikolanu/336a0d032d71376799c8b8daa460680c#file-gistfile1-txt-L588
https://gist.github.com/vamshikolanu/336a0d032d71376799c8b8daa460680c#file-gistfile1-txt-L598
Drop table statements: …
> DBT-713: Add tests for Incremental full refresh

- tests/functional/adapter/test_utils.py
We don't need to overwrite the tests for both concat and hash functions. Hence removing these unnecessary changes as part of this PR.
https://jira.cloudera.com/browse/DBT-773
https://gist.github.com/nsharma-25/85d58132a4acd5172811e90f71d23499
> Changes in TestConcat and TestHash to make it consistent with changes in dbt-core

- dbt/adapters/hive/__version__.py
- dev-requirements.txt
- setup.py
Upgrading dbt-core version and dbt-hive adapter version to 1.6
https://jira.cloudera.com/browse/DBT-766
https://gist.github.com/vamshikolanu/c9efb1b5f03bff7073b682095bb6b196
> DBT-766: Upgrade dbt-core version and dbt-hive adapater version to 1.6

- README.md
Updating the version details in the descriptions and requirements
DBT-782 
N/A
> DBT-782: Update readme requirement to reflect right version

- README.md
- tests/functional/adapter/iceberg_files.py
- tests/functional/adapter/test_basic.py
- tests/functional/adapter/test_iceberg_v1.py
- tests/functional/adapter/test_iceberg_v2.py
Adding functional tests for merge incremental strategy of ACID and iceberg tables of hive. Tests have been added for 
1. Acid tables
2. Iceberg v1 format
3. Iceberg v2 format
1. Acid tables: https://gist.github.com/vamshikolanu/1f109adf1c198d9c593dd0d3e4551381
2. Iceberg v1 format: https://gist.github.com/vamshikolanu/9688a7d90ddc322518ff9e15fe1115a4
3. Iceberg v2 format: https://gist.github.com/vamshikolanu/653d44cf3dacec755c6584ae6163a220
All tests: https://gist.github.com/vamshikolanu/4bd62ed0068cce9db6bfdb8291546e7c
> Add functional tests for merge incremental strategy of ACID and iceberg tables of hive
