cloudera/dbt-hive

dbt/adapters/hive/connections.py
dbt/adapters/hive/impl.py

Currently hive adapter uses global logging and it doesn't log information to dbt log. This will enable local adapter specific logging for better debugging.
tested by knowingly introducing errors in dbt project and doing a run

Add logging feature

---

dbt/adapters/hive/connections.py

Our impyla driver takes care of properly reading strings. Adding quotes manually is not necessary.
Tested with dbt seed and manual testing
DDbt test cases that were failing earlier now passes

DBT-225 fix for extra quotes added to strings

---

dbt/adapters/hive/connections.py

Pass auth_mechanism='PLAIN' when connecting to local Hive instance, without this the connection fails for a local unsecured setup.
Testplan:
- Setup local hive instance (for insance use this docker image: https://github.com/big-data-europe/docker-hive)
- Test dbt debug using profile:
<pre>
dev_hive_local:
type: hive
host: localhost
port: 10000
schema: dbtdemo
</pre>

fix an issue that prevented connection to local hive instance

---

dbt/include/hive/macros/adapters.sql

To use external table, the model config needs to use external=true property. For instance:
<pre>
{{
config(
materialized='table',
external=true
)
}}
</pre>

Support external table.

---

dbt/include/hive/macros/adapters.sql
dbt/include/hive/macros/materializations/incremental/incremental.sql

Add a macro to get the Hive version to determine if the incremental merge is supported by warehouse.
The PR will check the Hive version for an incremental merge run and if the version is not 3, will fail.

Use Hive version to determine if merge is supported

---

dbt/adapters/hive/connections.py

Testplan:
To use kerberos use a profile file similar to the following: 
<pre>
dbtdemo:
target: dev_hive_kerberos
outputs:
dev_hive_kerberos:
type: hive
host: [host]
port: [port]
auth_type: GSSAPI
kerberos_service_name: [kerberos service name]
use_http_transport: false
use_ssl: true
schema: dbtdemo
threads: 1
</pre>
Usually the steps are:
(a) kinit to generate keytab
(b) use dbt debug to test connectivity

add kerberos support

---

dbt/adapters/hive/connections.py

Internal ticket: https://jira.cloudera.com/browse/DBT-372
The error printed seems to be generic, so adding
code to identity the failure from Hive connection.
Test plan:
* Move into a dbt hive project and install dbt-hive from this git repo
* Add profile details in your home dbt file like below, 
dbt_hive_demo:
outputs:
dev_cia_cdp:
auth_type: ldap
host: {}
http_path: {}
password: {}
port: 443
schema: dbt_hive_demo
threads: 4
type: hive
use_http_transport: true
use_ssl: true
user: {}
target: dev_cia_cdp
* Update with wrong hostname or wrong user credentials
* run > dbt debug, and you should see the type of error in the console
* Add below snowplow configs to your .env if you face any snowplow error SNOWPLOW_ENDPOINT=https://dcevents.cldrteam.datacoral.io/cldrteam/apievents …

Add http error identification for credentials and hostname errors

---

dbt/adapters/hive/connections.py

Add query instrumentation.
Capture query_type, query_status, elapsed_time (for query execution) 
Internal: https://jira.cloudera.com/browse/DBT-386
With a dbt debug, check the output in logs/dbt.log, there should be an entry similar to:
(for query start)
06:41:59.880807 [debug] [Thread-1  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_hive_start_query", "profile_name": "dbtdemo", "sql_type": "select 1", "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "id": "3fae327d-2a42-4fb9-9106-db9a05b51e85", "unique_host_hash": "cd2782200d6326126da659d53c3dfe44", "unique_user_hash": "3d23971613757087a31726e1b95f7b57", "unique_session_hash": …

Add query instrumentation

---

dbt/adapters/hive/cloudera_tracking.py

1. In some environemnts such as pytest for running functional tests, active_user is not available and causes a runtime exception. This PR simiply checks if a valid active_user object is available before attempting to use it.
2. Addresses a data format issue with the data being sent for instrumentation.

fix issues with cloudera instrumentation

---

dbt/include/hive/macros/utils/listagg.sql
tests/functional/adapter/test_utils.py

Support for list agregation macro
(venv_hive) spulapura@Sujits-MacBook-Pro dbt-hive % python -m pytest tests/functional/adapter/test_utils.py -k "TestListAgg"
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.10.7, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/spulapura/DBT_HIVE/dbt-hive-migration/dbt-hive
collected 19 items / 18 deselected / 1 selected
tests/functional/adapter/test_utils.py .                                                                                                                                               [100%]
====================================================================================== …

Changes to support list aggregation macro

---

dbt/adapters/hive/impl.py
dbt/include/hive/macros/apply_grants.sql
dbt/include/hive/macros/materializations/incremental/incremental.sql
dbt/include/hive/macros/materializations/table.sql
tests/functional/adapter/test_grants.py

* grants support 
python -m pytest tests/functional/adapter/test_grants.py -k 'TestInvalidGrantsHive'
<pre>
collected 4 items / 3 deselected / 1 selected
tests/functional/adapter/test_grants.py .                                [100%]
================= 1 passed, 3 deselected in 130.50s (0:02:10) ==================
</pre>
python -m pytest tests/functional/adapter/test_grants.py -k 'TestModelGrantsHive'
<pre>
rootdir: …

grants support

---

dbt/include/hive/macros/utils/datediff.sql
tests/functional/adapter/test_utils.py

support for datediff macro
<pre>
(dev-dbt-hive) ganesh.venkateshwara@ganesh dbt-hive % python -m pytest tests/functional/adapter/test_utils.py -k 'TestDateDiff'                     
==================================================================================== test session starts =====================================================================================
collected 20 items / 19 deselected / 1 selected                                                                                                                                              
tests/functional/adapter/test_utils.py . …

support for datediff

---

dbt/adapters/hive/connections.py

Tested with macros that caused this error:
<pre>
(dev-dbt-hive) ganesh.venkateshwara@ganesh dbt-hive % python -m pytest tests/functional/adapter/test_utils.py -k 'TestConcat' 
==================================================================================== test session starts =====================================================================================
collected 20 items / 19 deselected / 1 selected                                                                                                                                              
tests/functional/adapter/test_utils.py . …

fix and issue when using dbt seed with number values of 0 would get converted to NULL

---

tests/functional/adapter/test_basic.py

adds a new test TestBaseIncrementalNotSchemaChange for dbt-core==1.3
Test result:
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestBaseIncrementalNotSchemaChange'
collected 9 items / 8 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
================= 1 passed, 8 deselected in 214.54s (0:03:34) ==================
</pre>

add new test TestBaseIncrementalNotSchemaChange

---

dbt/include/hive/macros/materializations/incremental/strategies.sql

add hive__get_incremental_default_sql() macro that returns the default incremental sql 
Test result:
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestIncrementalHive'
collected 9 items / 8 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
================= 1 passed, 8 deselected in 336.46s (0:05:36) ==================
</pre>

add hive__get_incremental_default_sql() macro

---

dbt/adapters/hive/cloudera_tracking.py
dbt/adapters/hive/impl.py

fixes issue with nested json for:
warehouse_version
dbt_deployment_env
permissions
Perform a dbt debug and check the logs for Tracking data. Set a DBT_DEPLOYMENT_ENV and check the logs.
Sample json payload from the logs attached:
<pre>
[0m13:57:17.202295 [debug] [Thread-9  ]: Tracker adapter: Sending Event {'data': '{"event_type": "dbt_hive_warehouse", "warehouse_version": [{"_c0": "3.1.3000.7.2.15.4-6 r5675879824372d3800b4d655226bc5b45b6e8c2e"}], "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "c424bacb-ef57-4ad4-a41c-7be5e06410e4", "unique_host_hash": "753b4c858f38bb52b2db7b3c8e7569e6", "unique_user_hash": …

fix issues with nested json for cloudera_tracking payload

---

dbt/include/hive/macros/materializations/incremental/incremental.sql

restructure incremental implementation to follow default dbt-core implementation
Test 1 (functional test)
<pre>
(dev-dbt-hive) ganesh.venkateshwara@ganesh dbt-hive % python -m pytest tests/functional/adapter/test_basic.py -k 'TestIncrementalHive' | tee test-incremental3.log
collected 9 items / 8 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
================= 1 passed, 8 deselected in 387.35s (0:06:27) ==================
</pre>
Test 2 (sample and dbt-hive-example)
<pre>
(dev-dbt-hive) ganesh.venkateshwara@ganesh dbtdemo % dbt run -t …

restructure incremental implementation to follow default

---

dbt/adapters/hive/cloudera_tracking.py

split dbt_adapter field in instrumentation to dbt_adapter_type and dbt_adapter_version
Test Result:
{'data': '{"event_type": "dbt_hive_close", "connection_state": "closed", "elapsed_time": "0.96", "auth": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "684e574f-fe52-4662-9524-090f87575bfb", "unique_host_hash": "753b4c858f38bb52b2db7b3c8e7569e6", "unique_user_hash": "e8a5d78ea632435d797d3d58df650872", "unique_session_hash": "cf2160b816331e0f0e7e6d8dd1e523f8", "python_version": "3.10.7", "system": "Darwin", "machine": "arm64", "platform": "macOS-13.0.1-arm64-arm-64bit", "dbt_version": "1.3.1", **"dbt_adapter_type": "hive", "dbt_adapter_version": "1.3.0"**, "dbt_deployment_env": {}, …

split dbt_adapter field in instrumentation to dbt_adapter_type and dbt_adapter_version

---

dbt/adapters/hive/connections.py

Merge node_id and model_name into one key: model_name
Sample event payload:
<pre>
[0m10:43:31.398126 [debug] [Thread-33 ]: Tracker adapter: Sending Event {'data': '{"event_type": "dbt_hive_model_access", "model_name": "dbtdemo.my_first_dbt_model", "model_type": "table", "incremental_strategy": "", "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "1acff133-c7d3-44a2-a8d1-d47868ca3b09", "unique_host_hash": "753b4c858f38bb52b2db7b3c8e7569e6", "unique_user_hash": "e8a5d78ea632435d797d3d58df650872", "unique_session_hash": "e6582a6a226efe74bc9c41af822aa051", "python_version": "3.9.12", "system": "Darwin", "machine": "arm64", "platform": "macOS-13.0.1-arm64-arm-64bit", "dbt_version": "1.3.1", …

merge node_id and model_name into one key: model_name

---

tests/functional/adapter/test_utils.py

test_utils.py::TestBoolOr were broken because the query is using the reserved word **key**. 
Base test uses key_column, hence removed the overridden query
https://jira.cloudera.com/browse/DBT-714
Before https://gist.github.com/niteshy/1f415a2dc0736e402e01e9bb4631669c
After https://gist.github.com/niteshy/b34a63919262bbbd14b33098dfa0028d

DBT-714: Fixing the TestBoolOr test, remove the usage of keyword key from the query

---

tests/functional/adapter/test_grants.py

grants test required the two capabilities 
1. test user should have show grants privileges
2. is the grant or ranger is better approach to handle the permissions   
For now, skipping the tests to allow full test to run. 
https://jira.cloudera.com/browse/DBT-716
https://gist.github.com/niteshy/8e34dd4ace6da3883de3ea0fcdda8d3c

DBT-716: Skipping grants tests as grants might not be supported in hive sql

---

dbt/include/hive/macros/adapters.sql
tests/functional/adapter/test_table_type.py

To added a support for table_type option as iceberg. This is more standard configuration and compatible with dbt-impala configuration. 
Also added the functional tests for normal and incremental strategies. 
Note: Partitions Tests are skipped because of bug in the incremental insert queries.  
https://jira.cloudera.com/browse/DBT-712
https://gist.github.com/niteshy/7add114dd703743e6d638411b07b350e

DBT-712: added support for table-type as iceberg and tests

---

tests/functional/adapter/test_docs.py

Currently, the test_docs.py are failing because of a mismatch in the value of `owner` attributes in the `describe formatted <table>` output. We have inconsistent behavior of describe output, hence skipping docs tests. 
https://jira.cloudera.com/browse/DBT-729
https://gist.github.com/niteshy/71f9b01efeaee254511bb986a891fd79

DBT-729: Skipping docs tests because of inconsistent behavior owner attributes

---

dbt/adapters/hive/impl.py
tests/functional/adapter/test_basic.py
tests/functional/adapter/test_table_type.py

Insert query required the list of columns in the tables. We use the `describe formatted` command to find the table metadata like columns, partition columns, etc. Currently, the `describe formatted` has compatibility issues like following
1. `describe formatted <table>` for normal tables is not returning the partition columns in the columns list vs iceberg tables output has partition columns in the main list, and also in the partition sections too. 
2. `describe formatted <table>` has different partition section headers eg `# Partition Information` used for non-iceberg
Vs `"# Partition Transform Information` used for iceberg table. 
To handle these issues, we are parsing and aggregating the column list from main section and partition sections. Using it as collective columns list. …

DBT-728: Fixed the handling of partition columns in hive

---

dbt/adapters/hive/connections.py
setup.py
tests/conftest.py

The Python `Kerberos` module is only available on Unix/Linux platforms, so dbt-hive installation failed on the Windows platform. 
To resolve the issue, we are installing the modules based on the platform. Even though we have installed the Winkerberos module for Windows. At this time, it is difficult to setup the Kerberos setup for windows. Hence, we qualified the windows using non-kerberos (LDAP) endpoint
https://jira.cloudera.com/browse/DBT-718
Kerberos Setup https://gist.github.com/niteshy/435e3efeded42c56663979180a3f8ba9 
Mac Testing 
Using Kerberos endpoint https://gist.github.com/niteshy/14d467a78d2f162c6bea5efab3340acc 
Using non-Kerberos (LDAP) endpoint https://gist.github.com/niteshy/39d2414f232637b513590517ff606f72 
Linux Testing 
Using Kerberos endpoint …

DBT-718: Handling the kerberos module installation for different platforms

---

dbt/include/hive/macros/materializations/incremental/strategies.sql
tests/functional/adapter/test_basic.py
tests/functional/adapter/test_table_type.py

For the incremental overwrite strategy (iceberg), insert statements are failing for tables containing partition columns. 
Previously, insert queries has a partition clause which is not supported for the iceberg table eg.
```
insert overwrite table incremental
partition (id_partition)
select `id`, `name`, `some_date`, `id_partition` from incremental__dbt_tmp;
```
After fix 
```
insert overwrite table incremental_test_model
select `id`, `name`, `some_date`, `id_partition1` from incremental_test_model__dbt_tmp;
```
https://jira.cloudera.com/browse/DBT-731
https://gist.github.com/niteshy/6f73c1dd590250d3c8050543e978bbda

DBT-731: Iceberg: Fixing the incremental overwrite strategy, insert statements

---

dbt/include/hive/macros/adapters.sql
tests/functional/adapter/iceberg_files.py
tests/functional/adapter/test_iceberg_v1.py
tests/functional/adapter/test_iceberg_v2.py
tests/functional/adapter/test_table_type.py

As part of this change, Added support for format-version which enables users to create iceberg tables with v2 spec.
https://jira.cloudera.com/browse/DBT-736
https://gist.github.com/vamshikolanu/be8a77ebcda6216c12f118adcef8c13a

DBT-736: Add support for iceberg v2 spec 

---

dbt/include/hive/macros/materializations/incremental/incremental.sql
dbt/include/hive/macros/materializations/incremental/strategies.sql
tests/functional/adapter/iceberg_files.py
tests/functional/adapter/test_iceberg_v1.py
tests/functional/adapter/test_iceberg_v2.py

Currently for iceberg and non-partition tables, insert overwrite acts like a full refresh which is incorrect. 
The main idea behind the insert-overwrite strategy is to work with partitions. The insert overwrite strategy should ideally delete the data from selected partitions of the table and insert the newly transformed data into partitions. 
Hence removing the existing logic for iceberg and non-partition tables. In upcoming releases, we can support insert-overwrite for iceberg tables by removing the overlapping partitions and re-inserting the data. 
https://jira.cloudera.com/browse/DBT-738
https://gist.github.com/vamshikolanu/d2d6c0772e5dfb54149b472416bd7dde

DBT-738: Fix insert overwrite logic for iceberg and non-partition tables

---

dbt/adapters/hive/__version__.py
dbt/adapters/hive/connections.py
dev-requirements.txt
setup.py

Upgrading dbt-core to 1.5.10 resulted in the following issues: 
1. dbt-core surfaced two weeks ago [#9759](https://github.com/dbt-labs/dbt-core/issues/9759) when protobuf has released 5.26.0 version which is not compatible with dbt-core. Even though they fixed the issue by pining the version but the backports were NOT done correctly resulting in broken adapters. More details here https://github.com/dbt-labs/dbt-core/issues/9830. Causing issues #135
2. HiveCredentials extends the dbt-core Credentials class, which is required to implement the unique_field() method. This has caused the issues  #136
Resolve #135, #136
https://jira.cloudera.com/browse/DBT-763
https://jira.cloudera.com/browse/DBT-764
Verified the version upgrade and successful run of all tests …

DBT-763: DBT-764: Upgrading the dbt-core to v1.5.10 and resolving issues

---

dbt/include/hive/macros/utils/right.sql
tests/functional/adapter/test_utils.py

For TestRight, the current sql is mentioned below, however with this sql, in the case when length_epression = 0, we are getting NULL in actual column whereas in expected column of test_right we are getting an empty string, which is causing a mismatch between the expected and actual values.
```
create or replace view test_right
as
with util_data as (
select * from data_right
)
select
case when length_expression = 0
then NULL
else
substr(
string_text,
(length(string_text)-cast(length_expression as int)+1),
length(string_text)-1
)
end as actual,
coalesce(output, '') as expected
from util_data
```
This PR suggests to update the macro so that instead of NULL we get an empty string in the actual column.
https://jira.cloudera.com/browse/DBT-774
TestRight in v1.5 - …

DBT-774: Modifying the macro for TestRight to return empty string('') instead of NULL

---

dbt/include/hive/macros/utils/date_trunc.sql
tests/functional/adapter/test_utils.py

Currently the` date_trunc` macro for TestDateTrunc uses `trunc(string date, string format)` date function in which the supported formats are  MONTH/MON/MM, YEAR/YYYY/YY as mentioned in this doc(https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-DateFunctions) and due to this we are getting NULL as the actual value when `datepart='day'`, which leads to inconsistency between the actual and the expected value. 
As a part of this PR, I've updated the date_trunc macro thereby fixing the issue and at the time adding support for different other dateparts like microseconds, milliseconds, etc . I was able to achieve this with the below mentioned macro, where instead of trunc() function, date_format() function has been used.
```
{% macro hive__date_trunc(datepart, …
```

DBT-776: Add support for different  dateparts in date_trunc macro

---

dbt/include/hive/macros/utils/split_part.sql

Currently, split_part macros returns NULL when part_number is out of index. DBT expects the return value to be equal to empty string.
Example:
split_part('11.22.33', '.',  4) -> Previously returns NULL. After the change this returns ''.
https://jira.cloudera.com/browse/DBT-775
1.5 test: https://gist.github.com/vamshikolanu/06bc9f560178fb8d6ac32336d42af283
1.5 full tests: https://gist.github.com/vamshikolanu/399138cb7b9e88244bd5b5598c1e92fc
1.6 test: https://gist.github.com/vamshikolanu/f9768bad825e04fd297676e1718a3fc3

DBT-775: Fix split part macro to return empty string instead of null

---

tests/functional/adapter/test_utils.py

order_by, limit_num doesn't work for listagg macro of Hive. Hence removing the union all clause for the same.
https://jira.cloudera.com/browse/DBT-777
TestListagg(v1.5)- https://gist.github.com/nsharma-25/3dfa58aa1d38cad6ed183684f47a2eac
TestListagg(v1.6)- https://gist.github.com/nsharma-25/fee30d7a2d982e469667f8b23340c1c3
All Tests(v1.5)-  https://gist.github.com/nsharma-25/161b5473730462ae41124134e9e9a086

DBT-777: Fixing functional tests of TestListagg macro

---

README.md
dbt/adapters/hive/__version__.py
dbt/adapters/hive/column.py
dev-requirements.txt
setup.py

Upgrade dbt-core version and dbt-hive adapater version to 1.7
dbt-core has removed hologram dependency as part of this PR: https://github.com/dbt-labs/dbt-core/pull/8437/files
Hence removing it from dbt-hive too.
https://jira.cloudera.com/browse/DBT-778
https://gist.github.com/nsharma-25/d1d1b7efe99539a9c92234bb2238cab4

DBT-778: Upgrade dbt-core version and dbt-hive adapater version to 1.7

---

README.md
dbt/adapters/hive/__version__.py
dbt/adapters/hive/cloudera_tracking.py
dbt/adapters/hive/column.py
dbt/adapters/hive/connections.py
dbt/adapters/hive/impl.py
dbt/adapters/hive/relation.py
dev-requirements.txt
setup.py

Upgraded dbt-hive adapter to support dbt-core version of 1.8.*. The [migration guide
](https://github.com/dbt-labs/dbt-adapters/discussions/87) and this [PR](https://github.com/cloudera/dbt-hive/pull/149) were used as a reference. As suggested by the migration guide following changes were done 
- imports were shifted to new module/package structure of dbt-core. 
- functional/semantic code changes to reflect new method signatures. 
No changes to tests and macros were required at this point. 
@vamshikolanu 
In one of the test classes, I came across a file called manifest.json, is this the same manifest file that is required by adapter to access database objects? 
https://jira.cloudera.com/browse/DBT-783
Tests run on all python versions …

DBT-783 Support dbt-core 1.8.0 for dbt-hive

---

README.md
dbt/adapters/hive/__version__.py
dev-requirements.txt
setup.py
tests/functional/adapter/test_concurrency.py

Upgraded **dbt-hive** adapter to support **dbt-core** version of **1.10.***
https://cloudera.atlassian.net/browse/DBT-822
https://gist.github.com/niranjancdw/8c211aa9f533f2068eb1e2f427fe46d9

DBT-822 Support dbt-core 1.10.0 for dbt-hive
